version: "3.9"

services:
  # ------------------------------------------------------
  # 🌐 FRONTEND (Next.js)
  # ------------------------------------------------------
  konyx-frontend:
    container_name: konyx-frontend
    image: konyx-frontend:version2
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      lan-local:
        ipv4_address: 192.168.1.50
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://192.168.1.51:8000
    depends_on:
      - konyx-backend

  # ------------------------------------------------------
  # ⚙️ BACKEND (FastAPI)
  # ------------------------------------------------------
  konyx-backend:
    container_name: konyx-backend
    image: konyx-backend:version2
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      lan-local:
        ipv4_address: 192.168.1.51
    restart: unless-stopped
    volumes:
      - ./backend/app/data.json:/app/data.json
    environment:
      - TZ=Europe/Madrid
    expose:
      - "8000"

# ------------------------------------------------------
# 🧩 RED EXISTENTE (macvlan)
# ------------------------------------------------------
networks:
  lan-local:
    external: true
