version: "3.9"
services:
  backend:
    build: ./backend
    container_name: konyx-backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    container_name: konyx-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://backend:8000"
    depends_on:
      - backend
