name: Build & Publish Docker images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ghcr.io/vcaseta/konyx-backend:latest

      - name: Build & Push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/vcaseta/konyx-frontend:latest
          build-args: |
            NEXT_PUBLIC_BACKEND_URL=http://192.168.1.51:8000
            NEXT_PUBLIC_APP_NAME=Konyx
            NEXT_PUBLIC_COMPANIES=[{"id":"001","name":"Kissoro"},{"id":"002","name":"En Plural Psicologia"}]

      - name: Clean up Docker Buildx
        run: docker buildx prune --all --force
