name: Build & Deploy Docker images (version2)

on:
  push:
    branches:
      - version2

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      # 1️⃣ Clonar repositorio
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node.js para frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Cache frontend node_modules
      - name: Cache frontend node_modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-frontend-${{ hashFiles('frontend/package-lock.json') }}

      # 4️⃣ Crear package-lock.json si no existe
      - name: Ensure frontend lockfile
        run: npm install --package-lock-only
        working-directory: ./frontend

      # 5️⃣ Instalar dependencias frontend
      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      # 6️⃣ Build frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      # 7️⃣ Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 8️⃣ Log in a GHCR con usuario personal
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 9️⃣ Build & Push backend Docker (FastAPI)
      - name: Build & Push backend Docker
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.actor }}/konyx-backend:version2

      # 🔟 Build & Push frontend Docker
      - name: Build & Push frontend Docker
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.actor }}/konyx-frontend:version2
          build-args: |
            NEXT_PUBLIC_BACKEND_URL=http://192.168.1.51:8000
            NEXT_PUBLIC_APP_NAME=Konyx
            NEXT_PUBLIC_COMPANIES='[{"id":"001","name":"Kissoro"},{"id":"002","name":"En Plural Psicologia"}]'

      # 11️⃣ Limpiar Buildx cache
      - name: Clean up Docker Buildx
        run: docker buildx prune --all --force
