name: Build and Publish Version2

on:
  push:
    branches:
      - version2

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -------------------- Frontend --------------------
      - name: Build frontend image
        run: docker build -t ghcr.io/${{ github.repository }}/konyx-frontend:version2 ./frontend

      - name: Push frontend image
        run: docker push ghcr.io/${{ github.repository }}/konyx-frontend:version2

      # -------------------- Backend --------------------
      - name: Build backend image
        run: docker build -t ghcr.io/${{ github.repository }}/konyx-backend:version2 ./backend

      - name: Push backend image
        run: docker push ghcr.io/${{ github.repository }}/konyx-backend:version2
